---
- name: Set Password
  hosts: all
  become: yes
  ignore_errors: yes
  tasks:
      - name: Change root password
        user:
          name: root
          password: $dff2878927319283198439843hjsddhdkjch823787431213413dwfwfvwgwwq
          update_password: always


